[package]
name = "Pathfinder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
ordered-float = "3.7"
priority-queue = "1.3"

macroquad = "0.3.25"
rand = "0.8.5"
