name: Java Formatting
on:
  push:
    branches: [main]



jobs:
 format:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: axel-op/googlejavaformat-action@v3
       with:
         args: "--replace"
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
         distribution: temurin
         java-version: 11

     
     - name: Gradle Build 
       uses: gradle/gradle-build-action@v2
       with:
         arguments: build

     - name: Gradle test
       uses: gradle/gradle-build-action@v2
       with:
         arguments: test

