name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
   
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Gradle Test 
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
