name: Run Gradle on PRs
on:
  pull_request:

  push:
    branches: main
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
   
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Gradle Test 
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
