name: Gradle Build & Test
on:
  pull_request:

  push:
jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - uses: stefanzweifel/git-auto-commit-action@v4
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Gradle Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
